version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-auto-publisher-dev
    ports:
      - "5000:5000"
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - FLASK_PORT=5000
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - linkedin-net
    command: python main.py

networks:
  linkedin-net:
    driver: bridge