services:
  frontend:
    build: ./frontend
    container_name: linkedin-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - TZ=Europe/Paris
    networks:
      - linkedin-net
    restart: unless-stopped

  backend:
    build: .
    container_name: linkedin-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - FLASK_PORT=5000
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - linkedin-net

  # Optional: Add a separate database service (PostgreSQL instead of SQLite for production)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: linkedin-db
  #   environment:
  #     POSTGRES_DB: linkedin_posts
  #     POSTGRES_USER: linkedin_user
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - linkedin-net

networks:
  linkedin-net:
    driver: bridge

volumes:
  postgres_data: